// <auto-generated />
using BotMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BotMonitor.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20180217235433_AddInstruction")]
    partial class AddInstruction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("BotMonitor.Models.Bot", b =>
                {
                    b.Property<byte>("Id");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(32);

                    b.Property<DateTime>("LastUpdated");

                    b.Property<byte>("Level");

                    b.Property<string>("Name")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("BotMonitor.Models.Instruction", b =>
                {
                    b.Property<byte>("Id");

                    b.Property<byte>("BotId");

                    b.Property<string>("Command");

                    b.HasKey("Id");

                    b.HasIndex("BotId")
                        .IsUnique();

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("BotMonitor.Models.Instruction", b =>
                {
                    b.HasOne("BotMonitor.Models.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
