// <auto-generated />
using BotMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BotMonitor.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20180217201505_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("BotMonitor.Models.Bot", b =>
                {
                    b.Property<byte>("Id");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(32);

                    b.Property<DateTime>("LastUpdated");

                    b.Property<byte>("Level");

                    b.Property<string>("Name")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.ToTable("Bots");
                });
#pragma warning restore 612, 618
        }
    }
}
